---
#author : Raja
##Version : 0.1
#To Configure tomcat on hosts

- hosts: tomcat
  remote_user: ec2-user
  become: yes

  tasks:
  - name: Installing Tomcat with other packages
    yum:
      name: "*"
      state: latest

  - name: Install java
    yum:
      name: java-1.8.0-openjdk
      state: latest

  - name: get tomcat from URL
    get_url:
      url: https://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.50/bin/apache-tomcat-9.0.50.tar.gz
      dest: /usr/local
      mode: '0777'

  - name: Unzip tomcat
    unarchive:
      src: /usr/local/apache-tomcat-9.0.50.tar.gz
      dest: /usr/local
      remote_src: yes
      mode: '0777'
